version: '3.3'
services:
    user:
        build: ./backend_modules/user
        ports:
            - "8080:8080"
    schedule:
        build: ./backend_modules/schedule
        ports:
            - "8081:8081"
        depends_on:
            - payment
    visit:
        build: ./backend_modules/visit
        ports:
            - "8082:8082"
        depends_on:
            - payment
            - user
    payment:
        build: ./backend_modules/payment
        ports:
            - "8083:8083"
    ui:
        build: ./frontend_modules/easy_clinic
        ports:
            - "3000:3000"
        depends_on:
            - user
            - payment
            - schedule
            - visit
        